// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVfmM12IuHVtxUbMttc8IzlG7Reok5xyQ',
    appId: '1:138332339517:web:0a87df5ca6ab914c81d954',
    messagingSenderId: '138332339517',
    projectId: 'interview-task-bd035',
    authDomain: 'interview-task-bd035.firebaseapp.com',
    storageBucket: 'interview-task-bd035.firebasestorage.app',
    measurementId: 'G-627K9DL9HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgD0KxRWPxwZVhL2esGCXlT5ITo0KlY-s',
    appId: '1:138332339517:android:591870662642dcbf81d954',
    messagingSenderId: '138332339517',
    projectId: 'interview-task-bd035',
    storageBucket: 'interview-task-bd035.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD90mcDQ4ZFdWBYZwPYfwKRXUSNFAF0u50',
    appId: '1:138332339517:ios:c6d1b51b693f3f0181d954',
    messagingSenderId: '138332339517',
    projectId: 'interview-task-bd035',
    storageBucket: 'interview-task-bd035.firebasestorage.app',
    iosBundleId: 'com.example.interviewTask',
  );

}